# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....types.analyze_batch_status_response import AnalyzeBatchStatusResponse
from ....types.page_info import PageInfo


class BatchesListResponse(UniversalBaseModel):
    data: typing.List[AnalyzeBatchStatusResponse] = pydantic.Field()
    """
    An array of batch objects. Each object includes item counts for each item status.
    """

    page_info: PageInfo

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
