# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.asset import Asset
from ...types.page_info import PageInfo


class AssetsListResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[Asset]] = pydantic.Field(default=None)
    """
    An array containing the assets.
    """

    page_info: typing.Optional[PageInfo] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
