# This file was auto-generated by Fern from our API Definition.

import contextlib
import json
import typing
from json.decoder import JSONDecodeError

from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.http_response import AsyncHttpResponse, HttpResponse
from .core.pydantic_utilities import parse_obj_as
from .core.request_options import RequestOptions
from .core.serialization import convert_and_respect_annotation_metadata
from .errors.bad_request_error import BadRequestError
from .errors.not_found_error import NotFoundError
from .errors.too_many_requests_error import TooManyRequestsError
from .types.analyze_image_input import AnalyzeImageInput
from .types.analyze_prompt_v_2 import AnalyzePromptV2
from .types.analyze_request_model_name import AnalyzeRequestModelName
from .types.analyze_stream_request_model_name import AnalyzeStreamRequestModelName
from .types.analyze_temperature import AnalyzeTemperature
from .types.analyze_text_prompt import AnalyzeTextPrompt
from .types.non_stream_analyze_response import NonStreamAnalyzeResponse
from .types.stream_analyze_response import StreamAnalyzeResponse
from .types.sync_response_format import SyncResponseFormat
from .types.video_context import VideoContext

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawBaseClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.contextmanager
    def analyze_stream(
        self,
        *,
        model_name: typing.Optional[AnalyzeStreamRequestModelName] = OMIT,
        video: typing.Optional[VideoContext] = OMIT,
        image: typing.Optional[typing.Sequence[AnalyzeImageInput]] = OMIT,
        prompt: typing.Optional[AnalyzeTextPrompt] = OMIT,
        prompt_v_2: typing.Optional[AnalyzePromptV2] = OMIT,
        temperature: typing.Optional[AnalyzeTemperature] = OMIT,
        response_format: typing.Optional[SyncResponseFormat] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        start_time: typing.Optional[float] = OMIT,
        end_time: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[StreamAnalyzeResponse]]]:
        """
        This method analyzes a video or one or more images and returns the results directly in the response. Each request must contain a video or one or more images, but not both. You can use general analysis (prompt-based text generation) with either media type.

        <Accordion title="Input requirements">
        **Videos**
        - Minimum duration: 1 second
        - Maximum duration: 1 hour
        - Formats: [FFmpeg supported formats](https://ffmpeg.org/ffmpeg-formats.html)
        - Resolution: 360x360 to 5184x2160 pixels
        - Aspect ratio: Between 1:1 and 1:2.4, or between 2.4:1 and 1:1.

        **Images**
        - You can provide one to twenty images per request.
        - Formats: JPEG, PNG, WebP, GIF, and BMP.
        - Maximum size: 20 MB per image.
        - Maximum pixel count: 16,777,216 pixels per image (width × height).
        </Accordion>

        **When to use this method**:
        - Analyze videos up to 1 hour, or analyze images
        - Retrieve immediate results without polling for task completion
        - Stream text fragments in real time for immediate processing and feedback

        **Do not use this method for**:
        - Videos longer than 1 hour. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.
        - Video segmentation with custom segment definitions. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.

        On the Free plan, you have a total of 600 minutes (10 hours) shared across indexing, analysis, and segmentation. For details, see the [Video hours and video count limits](/v1.3/docs/concepts/indexes#video-hours-and-video-count-limits) section.

        <Note title="Note">
        This endpoint is rate-limited. For details, see the [Rate limits](/v1.3/docs/get-started/rate-limits) page.
        </Note>

        Parameters
        ----------
        model_name : typing.Optional[AnalyzeStreamRequestModelName]
            The video understanding model to use for analysis.
            - `pegasus1.6`: For details about this version, see the [Pegasus 1.6](/v1.3/docs/concepts/models/pegasus/pegasus-1-6) page.
            - `pegasus1.5`: For details about this version, see the [Pegasus 1.5](/v1.3/docs/concepts/models/pegasus/pegasus-1-5) page.

            **Default:** `pegasus1.5`

        video : typing.Optional[VideoContext]

        image : typing.Optional[typing.Sequence[AnalyzeImageInput]]
            A list of up to twenty objects containing the images to analyze. For each image, include exactly one source. Requires Pegasus 1.6. Using any other model returns a `parameter_invalid` error.

            Mutually exclusive with the `video` and `prompt_v2` parameters. The `prompt` parameter is required when you provide images.

        prompt : typing.Optional[AnalyzeTextPrompt]
            A text prompt that guides the model on the desired format or content. To include reference images in your prompt, use the `prompt_v2` parameter instead. Mutually exclusive with the `prompt_v2` parameter.

            Your prompts can be instructive or descriptive, or you can phrase them as questions. This text counts toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        prompt_v_2 : typing.Optional[AnalyzePromptV2]
            A structured prompt that uses `<@name>` placeholders to reference images. Mutually exclusive with the `prompt` and `image` parameters.

            The prompt text and reference images count toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        temperature : typing.Optional[AnalyzeTemperature]

        response_format : typing.Optional[SyncResponseFormat]
            Specifies the format of the response. When you omit this parameter, the platform returns unstructured text. Only the `json_schema` type is supported for synchronous analysis.

        max_tokens : typing.Optional[int]
            The maximum response length, in tokens.

        start_time : typing.Optional[float]
            Start of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `end_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be less than `end_time` and the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        end_time : typing.Optional[float]
            End of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `start_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video plus its duration.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be greater than `start_time` and less than or equal to the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[StreamAnalyzeResponse]]]

        """
        with self._client_wrapper.httpx_client.stream(
            "analyze",
            method="POST",
            json={
                "model_name": model_name,
                "video": convert_and_respect_annotation_metadata(
                    object_=video, annotation=VideoContext, direction="write"
                ),
                "image": convert_and_respect_annotation_metadata(
                    object_=image, annotation=typing.Sequence[AnalyzeImageInput], direction="write"
                ),
                "prompt": prompt,
                "prompt_v2": convert_and_respect_annotation_metadata(
                    object_=prompt_v_2, annotation=AnalyzePromptV2, direction="write"
                ),
                "temperature": temperature,
                "response_format": convert_and_respect_annotation_metadata(
                    object_=response_format, annotation=SyncResponseFormat, direction="write"
                ),
                "max_tokens": max_tokens,
                "start_time": start_time,
                "end_time": end_time,
                "stream": True,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[StreamAnalyzeResponse]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            for _text in _response.iter_lines():
                                try:
                                    if len(_text) == 0:
                                        continue
                                    yield typing.cast(
                                        StreamAnalyzeResponse,
                                        parse_obj_as(
                                            type_=StreamAnalyzeResponse,  # type: ignore
                                            object_=json.loads(_text),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()

    def analyze(
        self,
        *,
        model_name: typing.Optional[AnalyzeRequestModelName] = OMIT,
        video: typing.Optional[VideoContext] = OMIT,
        image: typing.Optional[typing.Sequence[AnalyzeImageInput]] = OMIT,
        prompt: typing.Optional[AnalyzeTextPrompt] = OMIT,
        prompt_v_2: typing.Optional[AnalyzePromptV2] = OMIT,
        temperature: typing.Optional[AnalyzeTemperature] = OMIT,
        response_format: typing.Optional[SyncResponseFormat] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        start_time: typing.Optional[float] = OMIT,
        end_time: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[NonStreamAnalyzeResponse]:
        """
        This method analyzes a video or one or more images and returns the results directly in the response. Each request must contain a video or one or more images, but not both. You can use general analysis (prompt-based text generation) with either media type.

        <Accordion title="Input requirements">
        **Videos**
        - Minimum duration: 1 second
        - Maximum duration: 1 hour
        - Formats: [FFmpeg supported formats](https://ffmpeg.org/ffmpeg-formats.html)
        - Resolution: 360x360 to 5184x2160 pixels
        - Aspect ratio: Between 1:1 and 1:2.4, or between 2.4:1 and 1:1.

        **Images**
        - You can provide one to twenty images per request.
        - Formats: JPEG, PNG, WebP, GIF, and BMP.
        - Maximum size: 20 MB per image.
        - Maximum pixel count: 16,777,216 pixels per image (width × height).
        </Accordion>

        **When to use this method**:
        - Analyze videos up to 1 hour, or analyze images
        - Retrieve immediate results without polling for task completion
        - Stream text fragments in real time for immediate processing and feedback

        **Do not use this method for**:
        - Videos longer than 1 hour. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.
        - Video segmentation with custom segment definitions. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.

        On the Free plan, you have a total of 600 minutes (10 hours) shared across indexing, analysis, and segmentation. For details, see the [Video hours and video count limits](/v1.3/docs/concepts/indexes#video-hours-and-video-count-limits) section.

        <Note title="Note">
        This endpoint is rate-limited. For details, see the [Rate limits](/v1.3/docs/get-started/rate-limits) page.
        </Note>

        Parameters
        ----------
        model_name : typing.Optional[AnalyzeRequestModelName]
            The video understanding model to use for analysis.
            - `pegasus1.6`: For details about this version, see the [Pegasus 1.6](/v1.3/docs/concepts/models/pegasus/pegasus-1-6) page.
            - `pegasus1.5`: For details about this version, see the [Pegasus 1.5](/v1.3/docs/concepts/models/pegasus/pegasus-1-5) page.

            **Default:** `pegasus1.5`

        video : typing.Optional[VideoContext]

        image : typing.Optional[typing.Sequence[AnalyzeImageInput]]
            A list of up to twenty objects containing the images to analyze. For each image, include exactly one source. Requires Pegasus 1.6. Using any other model returns a `parameter_invalid` error.

            Mutually exclusive with the `video` and `prompt_v2` parameters. The `prompt` parameter is required when you provide images.

        prompt : typing.Optional[AnalyzeTextPrompt]
            A text prompt that guides the model on the desired format or content. To include reference images in your prompt, use the `prompt_v2` parameter instead. Mutually exclusive with the `prompt_v2` parameter.

            Your prompts can be instructive or descriptive, or you can phrase them as questions. This text counts toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        prompt_v_2 : typing.Optional[AnalyzePromptV2]
            A structured prompt that uses `<@name>` placeholders to reference images. Mutually exclusive with the `prompt` and `image` parameters.

            The prompt text and reference images count toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        temperature : typing.Optional[AnalyzeTemperature]

        response_format : typing.Optional[SyncResponseFormat]
            Specifies the format of the response. When you omit this parameter, the platform returns unstructured text. Only the `json_schema` type is supported for synchronous analysis.

        max_tokens : typing.Optional[int]
            The maximum response length, in tokens.

        start_time : typing.Optional[float]
            Start of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `end_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be less than `end_time` and the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        end_time : typing.Optional[float]
            End of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `start_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video plus its duration.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be greater than `start_time` and less than or equal to the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[NonStreamAnalyzeResponse]

        """
        _response = self._client_wrapper.httpx_client.request(
            "analyze",
            method="POST",
            json={
                "model_name": model_name,
                "video": convert_and_respect_annotation_metadata(
                    object_=video, annotation=VideoContext, direction="write"
                ),
                "image": convert_and_respect_annotation_metadata(
                    object_=image, annotation=typing.Sequence[AnalyzeImageInput], direction="write"
                ),
                "prompt": prompt,
                "prompt_v2": convert_and_respect_annotation_metadata(
                    object_=prompt_v_2, annotation=AnalyzePromptV2, direction="write"
                ),
                "temperature": temperature,
                "response_format": convert_and_respect_annotation_metadata(
                    object_=response_format, annotation=SyncResponseFormat, direction="write"
                ),
                "max_tokens": max_tokens,
                "start_time": start_time,
                "end_time": end_time,
                "stream": False,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    NonStreamAnalyzeResponse,
                    parse_obj_as(
                        type_=NonStreamAnalyzeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawBaseClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.asynccontextmanager
    async def analyze_stream(
        self,
        *,
        model_name: typing.Optional[AnalyzeStreamRequestModelName] = OMIT,
        video: typing.Optional[VideoContext] = OMIT,
        image: typing.Optional[typing.Sequence[AnalyzeImageInput]] = OMIT,
        prompt: typing.Optional[AnalyzeTextPrompt] = OMIT,
        prompt_v_2: typing.Optional[AnalyzePromptV2] = OMIT,
        temperature: typing.Optional[AnalyzeTemperature] = OMIT,
        response_format: typing.Optional[SyncResponseFormat] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        start_time: typing.Optional[float] = OMIT,
        end_time: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[StreamAnalyzeResponse]]]:
        """
        This method analyzes a video or one or more images and returns the results directly in the response. Each request must contain a video or one or more images, but not both. You can use general analysis (prompt-based text generation) with either media type.

        <Accordion title="Input requirements">
        **Videos**
        - Minimum duration: 1 second
        - Maximum duration: 1 hour
        - Formats: [FFmpeg supported formats](https://ffmpeg.org/ffmpeg-formats.html)
        - Resolution: 360x360 to 5184x2160 pixels
        - Aspect ratio: Between 1:1 and 1:2.4, or between 2.4:1 and 1:1.

        **Images**
        - You can provide one to twenty images per request.
        - Formats: JPEG, PNG, WebP, GIF, and BMP.
        - Maximum size: 20 MB per image.
        - Maximum pixel count: 16,777,216 pixels per image (width × height).
        </Accordion>

        **When to use this method**:
        - Analyze videos up to 1 hour, or analyze images
        - Retrieve immediate results without polling for task completion
        - Stream text fragments in real time for immediate processing and feedback

        **Do not use this method for**:
        - Videos longer than 1 hour. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.
        - Video segmentation with custom segment definitions. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.

        On the Free plan, you have a total of 600 minutes (10 hours) shared across indexing, analysis, and segmentation. For details, see the [Video hours and video count limits](/v1.3/docs/concepts/indexes#video-hours-and-video-count-limits) section.

        <Note title="Note">
        This endpoint is rate-limited. For details, see the [Rate limits](/v1.3/docs/get-started/rate-limits) page.
        </Note>

        Parameters
        ----------
        model_name : typing.Optional[AnalyzeStreamRequestModelName]
            The video understanding model to use for analysis.
            - `pegasus1.6`: For details about this version, see the [Pegasus 1.6](/v1.3/docs/concepts/models/pegasus/pegasus-1-6) page.
            - `pegasus1.5`: For details about this version, see the [Pegasus 1.5](/v1.3/docs/concepts/models/pegasus/pegasus-1-5) page.

            **Default:** `pegasus1.5`

        video : typing.Optional[VideoContext]

        image : typing.Optional[typing.Sequence[AnalyzeImageInput]]
            A list of up to twenty objects containing the images to analyze. For each image, include exactly one source. Requires Pegasus 1.6. Using any other model returns a `parameter_invalid` error.

            Mutually exclusive with the `video` and `prompt_v2` parameters. The `prompt` parameter is required when you provide images.

        prompt : typing.Optional[AnalyzeTextPrompt]
            A text prompt that guides the model on the desired format or content. To include reference images in your prompt, use the `prompt_v2` parameter instead. Mutually exclusive with the `prompt_v2` parameter.

            Your prompts can be instructive or descriptive, or you can phrase them as questions. This text counts toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        prompt_v_2 : typing.Optional[AnalyzePromptV2]
            A structured prompt that uses `<@name>` placeholders to reference images. Mutually exclusive with the `prompt` and `image` parameters.

            The prompt text and reference images count toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        temperature : typing.Optional[AnalyzeTemperature]

        response_format : typing.Optional[SyncResponseFormat]
            Specifies the format of the response. When you omit this parameter, the platform returns unstructured text. Only the `json_schema` type is supported for synchronous analysis.

        max_tokens : typing.Optional[int]
            The maximum response length, in tokens.

        start_time : typing.Optional[float]
            Start of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `end_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be less than `end_time` and the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        end_time : typing.Optional[float]
            End of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `start_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video plus its duration.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be greater than `start_time` and less than or equal to the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[StreamAnalyzeResponse]]]

        """
        async with self._client_wrapper.httpx_client.stream(
            "analyze",
            method="POST",
            json={
                "model_name": model_name,
                "video": convert_and_respect_annotation_metadata(
                    object_=video, annotation=VideoContext, direction="write"
                ),
                "image": convert_and_respect_annotation_metadata(
                    object_=image, annotation=typing.Sequence[AnalyzeImageInput], direction="write"
                ),
                "prompt": prompt,
                "prompt_v2": convert_and_respect_annotation_metadata(
                    object_=prompt_v_2, annotation=AnalyzePromptV2, direction="write"
                ),
                "temperature": temperature,
                "response_format": convert_and_respect_annotation_metadata(
                    object_=response_format, annotation=SyncResponseFormat, direction="write"
                ),
                "max_tokens": max_tokens,
                "start_time": start_time,
                "end_time": end_time,
                "stream": True,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[StreamAnalyzeResponse]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            async for _text in _response.aiter_lines():
                                try:
                                    if len(_text) == 0:
                                        continue
                                    yield typing.cast(
                                        StreamAnalyzeResponse,
                                        parse_obj_as(
                                            type_=StreamAnalyzeResponse,  # type: ignore
                                            object_=json.loads(_text),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    if _response.status_code == 400:
                        raise BadRequestError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 429:
                        raise TooManyRequestsError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()

    async def analyze(
        self,
        *,
        model_name: typing.Optional[AnalyzeRequestModelName] = OMIT,
        video: typing.Optional[VideoContext] = OMIT,
        image: typing.Optional[typing.Sequence[AnalyzeImageInput]] = OMIT,
        prompt: typing.Optional[AnalyzeTextPrompt] = OMIT,
        prompt_v_2: typing.Optional[AnalyzePromptV2] = OMIT,
        temperature: typing.Optional[AnalyzeTemperature] = OMIT,
        response_format: typing.Optional[SyncResponseFormat] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        start_time: typing.Optional[float] = OMIT,
        end_time: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[NonStreamAnalyzeResponse]:
        """
        This method analyzes a video or one or more images and returns the results directly in the response. Each request must contain a video or one or more images, but not both. You can use general analysis (prompt-based text generation) with either media type.

        <Accordion title="Input requirements">
        **Videos**
        - Minimum duration: 1 second
        - Maximum duration: 1 hour
        - Formats: [FFmpeg supported formats](https://ffmpeg.org/ffmpeg-formats.html)
        - Resolution: 360x360 to 5184x2160 pixels
        - Aspect ratio: Between 1:1 and 1:2.4, or between 2.4:1 and 1:1.

        **Images**
        - You can provide one to twenty images per request.
        - Formats: JPEG, PNG, WebP, GIF, and BMP.
        - Maximum size: 20 MB per image.
        - Maximum pixel count: 16,777,216 pixels per image (width × height).
        </Accordion>

        **When to use this method**:
        - Analyze videos up to 1 hour, or analyze images
        - Retrieve immediate results without polling for task completion
        - Stream text fragments in real time for immediate processing and feedback

        **Do not use this method for**:
        - Videos longer than 1 hour. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.
        - Video segmentation with custom segment definitions. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.

        On the Free plan, you have a total of 600 minutes (10 hours) shared across indexing, analysis, and segmentation. For details, see the [Video hours and video count limits](/v1.3/docs/concepts/indexes#video-hours-and-video-count-limits) section.

        <Note title="Note">
        This endpoint is rate-limited. For details, see the [Rate limits](/v1.3/docs/get-started/rate-limits) page.
        </Note>

        Parameters
        ----------
        model_name : typing.Optional[AnalyzeRequestModelName]
            The video understanding model to use for analysis.
            - `pegasus1.6`: For details about this version, see the [Pegasus 1.6](/v1.3/docs/concepts/models/pegasus/pegasus-1-6) page.
            - `pegasus1.5`: For details about this version, see the [Pegasus 1.5](/v1.3/docs/concepts/models/pegasus/pegasus-1-5) page.

            **Default:** `pegasus1.5`

        video : typing.Optional[VideoContext]

        image : typing.Optional[typing.Sequence[AnalyzeImageInput]]
            A list of up to twenty objects containing the images to analyze. For each image, include exactly one source. Requires Pegasus 1.6. Using any other model returns a `parameter_invalid` error.

            Mutually exclusive with the `video` and `prompt_v2` parameters. The `prompt` parameter is required when you provide images.

        prompt : typing.Optional[AnalyzeTextPrompt]
            A text prompt that guides the model on the desired format or content. To include reference images in your prompt, use the `prompt_v2` parameter instead. Mutually exclusive with the `prompt_v2` parameter.

            Your prompts can be instructive or descriptive, or you can phrase them as questions. This text counts toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        prompt_v_2 : typing.Optional[AnalyzePromptV2]
            A structured prompt that uses `<@name>` placeholders to reference images. Mutually exclusive with the `prompt` and `image` parameters.

            The prompt text and reference images count toward the [context window](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#context-window).

        temperature : typing.Optional[AnalyzeTemperature]

        response_format : typing.Optional[SyncResponseFormat]
            Specifies the format of the response. When you omit this parameter, the platform returns unstructured text. Only the `json_schema` type is supported for synchronous analysis.

        max_tokens : typing.Optional[int]
            The maximum response length, in tokens.

        start_time : typing.Optional[float]
            Start of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `end_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be less than `end_time` and the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        end_time : typing.Optional[float]
            End of the analysis window, as an absolute timestamp in seconds, based on the internal metadata of the video. Use with `start_time` to analyze only a portion of the video.

            <Note title="Notes">
            - If omitted, defaults to the internal start time of the video plus its duration.
            - Most videos start at 0, but some (for example, from cameras or broadcast recordings) may have a non-zero start time. To find the value, run `ffprobe -v error -show_entries format=start_time,duration -of default=noprint_wrappers=1 your_video.mp4`.
            - Must be greater than `start_time` and less than or equal to the video duration. The window (`end_time - start_time`) must be at least 1 second.
            </Note>

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[NonStreamAnalyzeResponse]

        """
        _response = await self._client_wrapper.httpx_client.request(
            "analyze",
            method="POST",
            json={
                "model_name": model_name,
                "video": convert_and_respect_annotation_metadata(
                    object_=video, annotation=VideoContext, direction="write"
                ),
                "image": convert_and_respect_annotation_metadata(
                    object_=image, annotation=typing.Sequence[AnalyzeImageInput], direction="write"
                ),
                "prompt": prompt,
                "prompt_v2": convert_and_respect_annotation_metadata(
                    object_=prompt_v_2, annotation=AnalyzePromptV2, direction="write"
                ),
                "temperature": temperature,
                "response_format": convert_and_respect_annotation_metadata(
                    object_=response_format, annotation=SyncResponseFormat, direction="write"
                ),
                "max_tokens": max_tokens,
                "start_time": start_time,
                "end_time": end_time,
                "stream": False,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    NonStreamAnalyzeResponse,
                    parse_obj_as(
                        type_=NonStreamAnalyzeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
