# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AnalyzeTaskWebhookError(UniversalBaseModel):
    """
    A message describing a task failure or why a ready general-analysis task has a partial result.
    """

    message: str = pydantic.Field()
    """
    A human-readable description of the failure or truncated output.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
