# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .analyze_task_segment_field_format import AnalyzeTaskSegmentFieldFormat
from .analyze_task_segment_field_items import AnalyzeTaskSegmentFieldItems


class AnalyzeTaskSegmentField(UniversalBaseModel):
    """
    A segment field from the request, returned as you provided it.
    """

    name: str = pydantic.Field()
    """
    The name of the field.
    """

    type: str = pydantic.Field()
    """
    The data type of the field.
    """

    description: typing.Optional[str] = None
    format: typing.Optional[AnalyzeTaskSegmentFieldFormat] = pydantic.Field(default=None)
    """
    The output format for `timestamp` fields.
    """

    enum: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The allowed values for this field.
    """

    items: typing.Optional[AnalyzeTaskSegmentFieldItems] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
