# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .analyze_task_failed_webhook_data import AnalyzeTaskFailedWebhookData
from .analyze_task_failed_webhook_event_type import AnalyzeTaskFailedWebhookEventType
from .analyze_task_webhook_event_base import AnalyzeTaskWebhookEventBase


class AnalyzeTaskFailedWebhookEvent(AnalyzeTaskWebhookEventBase):
    """
    A notification that an asynchronous analysis task reached the final `failed` status.
    """

    type: AnalyzeTaskFailedWebhookEventType = pydantic.Field()
    """
    The type of webhook event.
    """

    data: AnalyzeTaskFailedWebhookData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
