# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AnalyzeImageInput(UniversalBaseModel):
    """
    An image to analyze. Provide exactly one of `url`, `asset_id`, or `base64_string`.

    Each image can be up to 20 MB and 16,777,216 pixels (width × height). Supported formats: JPEG, PNG, WebP, GIF, and BMP. An image over either limit, or in another format, returns a `400` error.
    """

    name: str = pydantic.Field()
    """
    The name of this image. Must be unique within the `image` array. Can contain only letters, digits, and underscores.
    
    To refer to a specific image in your prompt, use its name as the `<@name>` placeholder. Reference every image or none of them:
    
    - If the prompt references every image, the platform analyzes each one (Example: `Compare <@before> with <@after> and describe what changed.`).
    - If the prompt references none of them, the platform analyzes every image you provided (Example: `List every visible feature in these images.`).
    - If the prompt references only some of the images, the platform returns a `400` error.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A publicly accessible HTTPS URL of the image. The platform rejects HTTP URLs.
    
    When you send the request, the platform verifies that the URL is reachable and that the image is within the [size, pixel count, and format limits](/v1.3/docs/concepts/models/pegasus/pegasus-1-6#image-file-requirements). If either check fails, the platform returns a `400` error.
    """

    asset_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of an uploaded asset.
    """

    base_64_string: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="base64_string")] = (
        pydantic.Field(default=None)
    )
    """
    Base64-encoded image data. The maximum decoded size is 20 MB. Supported image types: `image/jpeg`, `image/png`, `image/webp`, `image/gif`, and `image/bmp`. Standard and unpadded base64 encodings are both accepted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
