# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .asset_transcription_entry import AssetTranscriptionEntry
from .asset_transcription_error import AssetTranscriptionError
from .asset_transcription_status import AssetTranscriptionStatus
from .asset_transcription_utterance import AssetTranscriptionUtterance


class AssetTranscriptionResponse(UniversalBaseModel):
    """
    The transcription status and the transcriptions you requested.
    """

    status: AssetTranscriptionStatus
    words: typing.Optional[typing.List[AssetTranscriptionEntry]] = pydantic.Field(default=None)
    """
    One entry for each word. Present when the status is `ready`, the `include` parameter lists `words`, and the transcription supports word-level segmentation.
    """

    sentences: typing.Optional[typing.List[AssetTranscriptionEntry]] = pydantic.Field(default=None)
    """
    One entry for each chunk the speech recognition model detects as a sentence. Present when the status is `ready`, the `include` parameter lists `sentences`, and the transcription supports sentence-level segmentation.
    """

    utterances: typing.Optional[typing.List[AssetTranscriptionUtterance]] = pydantic.Field(default=None)
    """
    One entry for each speaker turn. Present when the status is `ready`, the `include` parameter lists `utterances`, and the transcription supports speaker-turn segmentation.
    """

    error: typing.Optional[AssetTranscriptionError] = pydantic.Field(default=None)
    """
    Details about the failure. Present when the status is `failed`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
