# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AssetTranscriptionUtterance(UniversalBaseModel):
    """
    A timestamped transcription entry for a speaker turn.
    """

    start: float = pydantic.Field()
    """
    The start timestamp in seconds.
    """

    end: float = pydantic.Field()
    """
    The end timestamp in seconds.
    """

    value: str = pydantic.Field()
    """
    The recognized text in this speaker turn.
    """

    speaker: typing.Optional[str] = pydantic.Field(default=None)
    """
    The speaker identifier when available.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
