# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .async_audio_input_request_embedding_option_item import AsyncAudioInputRequestEmbeddingOptionItem
from .async_audio_input_request_embedding_scope_item import AsyncAudioInputRequestEmbeddingScopeItem
from .async_audio_input_request_embedding_type_item import AsyncAudioInputRequestEmbeddingTypeItem
from .async_audio_input_request_segmentation import AsyncAudioInputRequestSegmentation
from .media_source import MediaSource
from .time_based_metadata_entry import TimeBasedMetadataEntry


class AsyncAudioInputRequest(UniversalBaseModel):
    """
    This field is required if the `input_type` parameter is `audio`.
    """

    media_source: MediaSource
    start_sec: typing.Optional[float] = pydantic.Field(default=None)
    """
    The start time in seconds for processing the audio file.
    
    Use this parameter to process a portion of the audio file starting from a specific time.
    
    **Default**: 0 (start from the beginning).
    """

    end_sec: typing.Optional[float] = pydantic.Field(default=None)
    """
    The end time in seconds for processing the audio file.
    
    Use this parameter to process a portion of the audio file ending at a specific time. The end time must be greater than the start time.
    
    **Default**: End of the audio file
    """

    segmentation: typing.Optional[AsyncAudioInputRequestSegmentation] = pydantic.Field(default=None)
    """
    Specifies how the platform divides the audio into segments.
    
    The structure of this object depends on the model version:
    
    - **With Marengo 3.5**: Place your settings in the `temporal` object. Both strategies are available: `dynamic` divides the audio into variable-length segments that follow scene changes, and `fixed` divides it into equal-length segments. Default: `temporal.dynamic`, `min_duration_sec: 2`.
    - **With Marengo 3.0**: Provide the settings directly in this object. Only `fixed` segmentation is available. Default: `fixed`, `duration_sec: 6`.
    
    Using a structure that does not match your model version returns a `400` error.
    """

    embedding_option: typing.Optional[typing.List[AsyncAudioInputRequestEmbeddingOptionItem]] = pydantic.Field(
        default=None
    )
    """
    The types of embeddings you wish to generate.
    
    **Values**:
    - `audio`: Generates embeddings based on audio content (sounds, music, effects). With Marengo 3.5, this value includes speech, music, and non-dialog audio.
    - `transcription`: Generates embeddings based on transcribed speech. Requires Marengo 3.0.
    
    You can specify multiple values to generate different types of embeddings for the same audio.
    
    **Default**: `["audio", "transcription"]` for Marengo 3.0; `["audio"]` for Marengo 3.5.
    """

    embedding_scope: typing.Optional[typing.List[AsyncAudioInputRequestEmbeddingScopeItem]] = pydantic.Field(
        default=None
    )
    """
    The scope for which you wish to generate embeddings.
    
    **Values**:
    - `clip`: Generates one embedding for each segment. Works with both Marengo 3.0 and Marengo 3.5.
    - `local`: Generates one embedding for each segment. Equivalent to `clip` when using Marengo 3.5.
    - `asset`: Generates one embedding for the entire audio file
    
    You can specify multiple scopes to generate embeddings at different levels.
    
    **Default**: `["clip", "asset"]`
    """

    embedding_type: typing.Optional[typing.List[AsyncAudioInputRequestEmbeddingTypeItem]] = pydantic.Field(default=None)
    """
    Specifies how to structure the embedding. Include this parameter only when the `embedding_option` parameter contains at least two values.
    
    **Values**:
    - `separate_embedding`: Returns separate embeddings for each modality specified in the `embedding_option` parameter.
    - `fused_embedding`: Returns a single combined embedding that integrates all modalities into one vector. With Marengo 3.5, this value requires the `time_based_metadata` field.
    
    Specify both values to receive separate and fused embeddings in the same response.
    
    **Default**: `separate_embedding`.
    """

    time_based_metadata: typing.Optional[typing.List[TimeBasedMetadataEntry]] = pydantic.Field(default=None)
    """
    Your own time-aligned text, such as a stats feed or scene descriptions. The platform folds each entry into the fused embedding of the segments it overlaps in time, and it affects only that embedding. Requires the `fused_embedding` value in the `embedding_type` field. This field is supported only with Marengo 3.5.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
