# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .async_response_format_type import AsyncResponseFormatType
from .segment_definition import SegmentDefinition


class AsyncResponseFormat(UniversalBaseModel):
    """
    Controls the response format. When you omit this parameter, you receive unstructured text.
    - `json_schema`: Return structured JSON that conforms to your schema.
    - `segment_definitions`: Extract timestamped metadata with custom fields from your video. Requires `model_name` set to `pegasus1.5` and `analysis_mode` set to `time_based_metadata`.
    """

    type: AsyncResponseFormatType = pydantic.Field()
    """
    The response format to use.
    - `json_schema`: Return structured JSON that conforms to your schema.
    - `segment_definitions`: Extract timestamped metadata with custom fields from your video. Requires `model_name` set to `pegasus1.5` and `analysis_mode` set to `time_based_metadata`.
    """

    json_schema: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Contains the JSON schema that defines the response structure. The schema must adhere to the [JSON Schema Draft 2020-12](https://json-schema.org/draft/2020-12) specification.
    
    **Supported types**
    - `array`
    - `boolean`
    - `integer`
    - `null`
    - `number`
    - `object`
    - `string`
    
    **Supported constraints**
    
    | Type | Supported keywords | Notes |
    |------|-------------------|-------|
    | `integer` | `maximum`, `exclusiveMaximum`, `minimum`, `exclusiveMinimum`. | - `maximum`: Sets the highest allowed value (inclusive).<br/>- `exclusiveMaximum`: Sets the highest allowed value (exclusive).<br/>- `minimum`: Sets the lowest allowed value (inclusive).<br/>- `exclusiveMinimum`: Sets the lowest allowed value (exclusive).<br/>These constraints are supported only for the `integer` type. |
    | `string` | `pattern`, `format` | - `pattern`: A regular expression that the string must match.<br/>- `format`: Validates predefined formats. It accepts the following values: `uuid`, `date-time`, `date`, and `time`.<br/>See string limitations below. |
    | `object` | `properties`, `required` | - `properties`: Defines object properties and their schemas. - `required`: Specifies mandatory properties.<br/>See object limitations below. |
    | `array` | `items`, `minItems` | `minItems` accepts only `0` or `1`.<br/>See array limitations below. |
    
    
    **String limitations**
    
    When you use the `string` type:
    - The platform validates strings using only `pattern` and `format`. Including `minLength` or `maxLength` causes a 422 error: "String length constraints (minLength) are not supported." Remove these keywords from your schema.
    
    
    **Object limitations**
    
    When you use the `object` type:
    - The platform does not support the `additionalProperties` keyword. Including it causes a 422 error. Remove it from your schema.
    - The platform returns properties in declaration order.
    - Make the first property required. If the first property is optional, the platform moves the first required property to the beginning.
    
    
    **Array limitations**
    
    When you use the `array` type:
    - The platform does not support `uniqueItems` or `maxItems`. Including either keyword causes a 422 error. Remove them from your schema.
    
    
    **Constant and enumerated values**
    
    The `const` and `enum` keywords support the following types:
    - `boolean`
    - `null`
    - `number`
    - `string`
    
    
    **Schema composition**
    
    The platform supports only `anyOf` for [schema composition](https://json-schema.org/understanding-json-schema/reference/combining).
    
    
    **Annotations**
    
    The platform accepts but ignores JSON schema annotations like `title`, `$comments`, and `description`.
    
    **Subschema references**
    
    You can reference subschemas using `$ref` with these requirements:
    - Define subschemas within `$defs`.
    - Use valid URIs that point to the internal subschema.
    
    For details, see the [JSON Schema documentation on $defs](https://json-schema.org/understanding-json-schema/structuring#defs).
    
    
    **Reserved property names (`start_time` / `end_time`)**
    
    When your response schema includes properties named `start_time` or `end_time`, the platform applies special type handling. These are unrelated to the top-level `start_time` / `end_time` request parameters or `time_ranges`. The model outputs these values as floating-point numbers representing seconds. The platform converts or rejects them based on the declared type in your schema.
    
    *Allowed types:*
    
    | Declared type | Platform behavior |
    |---------------|-------------------|
    | `number` | Passes the value through without conversion. |
    | `integer` | Rounds the value to the nearest integer. |
    | `string` (no `format`) | Converts the value to the `hh:mm:ss.fff` format. |
    
    *Rejected types (returns `400` error):*
    - `string` with any `format` keyword (`time`, `date-time`, `email`, `uri`, etc.)
    - `boolean`
    - `object`
    - `array`
    - `null`
    
    All other property names in your schema remain unconstrained by these rules.
    
    
    **Response validation**
    
    Check the `FinishReason` field to verify your JSON response is complete:
    - When `FinishReason` is `stop`, the generation completed normally, and the JSON is valid and complete.
    - When `FinishReason` is `length`, the platform truncates the response at the token limit. This may result in truncated, invalid JSON that fails to parse.
    """

    segment_definitions: typing.Optional[typing.List[SegmentDefinition]] = pydantic.Field(default=None)
    """
    Define the types of segments to extract from your video. Minimum 1, maximum 10 definitions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
