# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BaseEmbeddingMetadata(UniversalBaseModel):
    """
    Metadata about the embedding.
    """

    input_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL of the media file used to generate the embedding. Present if a URL was provided in the request.
    """

    input_filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the media file used to generate the embedding. Present if a file was provided in the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
