# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cancel_analyze_task_response_status import CancelAnalyzeTaskResponseStatus


class CancelAnalyzeTaskResponse(UniversalBaseModel):
    """
    The task identifier and the `canceled` status.
    """

    task_id: str = pydantic.Field()
    """
    The unique identifier of the analysis task.
    """

    status: CancelAnalyzeTaskResponseStatus = pydantic.Field()
    """
    The final status of the task.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
