# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .connection_account import ConnectionAccount
from .connection_provider import ConnectionProvider
from .connection_status import ConnectionStatus


class Connection(UniversalBaseModel):
    """
    A connection to an external data provider. The platform never returns the refresh or access tokens of the connection.
    """

    id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="_id")] = pydantic.Field(default=None)
    """
    The unique identifier of the connection.
    """

    provider: typing.Optional[ConnectionProvider] = pydantic.Field(default=None)
    """
    The data connector provider.
    """

    status: typing.Optional[ConnectionStatus] = pydantic.Field(default=None)
    """
    The status of the connection. See [The connection object](/v1.3/api-reference/data-connectors/the-connection-object#connection-statuses) for the possible values.
    """

    custom_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The label you supplied when creating the connection. The platform does not interpret this value, and it does not need to be unique. Multiple connections can share the same `custom_id` value.
    """

    account: typing.Optional[ConnectionAccount] = pydantic.Field(default=None)
    """
    Information about the connected provider account.
    """

    scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The scopes granted to the connection.
    """

    connected_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the connection was established.
    """

    last_used_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date and time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the connection was last used.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
