# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .batch_status import BatchStatus
from .created_batch_item import CreatedBatchItem


class CreateAnalyzeBatchResponse(UniversalBaseModel):
    """
    Response when creating a new batch.
    """

    batch_id: str = pydantic.Field()
    """
    The unique identifier of the batch.
    """

    status: BatchStatus
    total_items: int = pydantic.Field()
    """
    The number of items submitted in the batch.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The date and time, in the RFC 3339 format, when the batch was created.
    """

    expires_at: dt.datetime = pydantic.Field()
    """
    The date and time, in the RFC 3339 format, when the batch expires (the `created_at` field value plus 24 hours). Unfinished items at expiration are canceled. Items that finished before then remain retrievable for 30 days after creation, when the batch and its results are deleted.
    """

    items: typing.List[CreatedBatchItem] = pydantic.Field()
    """
    One entry per submitted item. Each entry pairs the unique task identifier generated by the platform with the custom identifier you provided when you created the batch.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
