# This file was auto-generated by Fern from our API Definition.

import typing

EmbeddingDataQuadrant = typing.Union[typing.Literal["top_left", "top_right", "bottom_left", "bottom_right"], typing.Any]
