# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EmbeddingImageMetadata(UniversalBaseModel):
    """
    Metadata for image embeddings
    """

    input_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The publicly accessible URL for the image
    """

    input_filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the image file
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
