# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EnrichmentConfigDescription(UniversalBaseModel):
    """
    Natural-language instructions that the platform converts into a JSON Schema internally.
    """

    description: str = pydantic.Field()
    """
    A natural-language description of what knowledge should be extracted from the videos.
    The platform converts this into a JSON Schema internally.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
