# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .base_embedding_metadata import BaseEmbeddingMetadata


class ImageEmbeddingMetadata(BaseEmbeddingMetadata):
    """
    An object containing metadata associated with the embedding. Only Marengo 3.5 returns this object.
    """

    image_embedding_option: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The `embedding_option` values used to generate the embedding. Always `["visual"]`.
    """

    image_embedding_scope: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The `embedding_scope` values used to generate the embedding. Always `["asset"]`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
