# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ImageMetadata(UniversalBaseModel):
    """
    System-generated media metadata for an image item.
    """

    filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    The original filename of the image.
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    The width of the image in pixels.
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    The height of the image in pixels.
    """

    codec_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The codec used to encode the image.
    """

    size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The file size of the image in bytes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
