# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .response_output_content_part import ResponseOutputContentPart
from .response_output_item_role import ResponseOutputItemRole
from .response_output_item_type import ResponseOutputItemType
from .response_status import ResponseStatus


class ResponseOutputItem(UniversalBaseModel):
    """
    An item in the response output. Items are polymorphic and discriminated by the `type` field.
    """

    type: ResponseOutputItemType = pydantic.Field()
    """
    The type of output item.
    """

    id: str = pydantic.Field()
    """
    A unique identifier for this item.
    """

    status: ResponseStatus
    role: typing.Optional[ResponseOutputItemRole] = pydantic.Field(default=None)
    """
    The role of the message author. Present when `type` is `message`.
    """

    phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Which part of the answer this message holds. Present when `type` is `message`.
    
    A turn can produce several messages: the model narrating what it is about to
    do, then the answer itself. `commentary` marks the narration and `final_answer`
    marks the answer, so picking the answer out of a turn does not mean guessing
    from item order.
    
    **`commentary` reaches you only when `include` is set to
    `["intermediate_outputs"]`.** That applies to streamed responses as well as
    non-streamed ones — the default keeps the final answer alone on both. When you
    do request it, a streamed message carries its `phase` on the
    `response.output_item.added` event, so a client can route the message before any
    of its text arrives.
    
    Treat a message with no `phase` as `final_answer`.
    
    Treat an unrecognized `phase` as narration rather than as the answer, so a
    phase this client does not know is never mistaken for it.
    """

    content: typing.Optional[typing.List[ResponseOutputContentPart]] = pydantic.Field(default=None)
    """
    The content parts of the message. Present when `type` is `message`.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the function. Present when `type` is `function_call`.
    """

    call_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for the function call. Present when `type` is `function_call`.
    """

    arguments: typing.Optional[str] = pydantic.Field(default=None)
    """
    The JSON-encoded arguments for the function call. Present when `type` is `function_call`.
    """

    output: typing.Optional[str] = pydantic.Field(default=None)
    """
    The function call output. Present when `type` is `function_call_output`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
