# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ResponseIncompleteDetails(UniversalBaseModel):
    """
    Details about why a response is incomplete. Present when the `status` field is
    `incomplete`.
    """

    reason: str = pydantic.Field()
    """
    The reason the answer is incomplete. The `max_output_tokens` value means
    the answer reached the output token limit. The text in the response is an
    incomplete answer, not the full one; treat an unrecognized value as an
    incomplete answer for an unknown reason, not as an error.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
