# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .response_annotation import ResponseAnnotation
from .response_output_content_part_type import ResponseOutputContentPartType


class ResponseOutputContentPart(UniversalBaseModel):
    """
    A content part within a message output item.
    """

    type: ResponseOutputContentPartType = pydantic.Field()
    """
    The type of content part.
    """

    text: str = pydantic.Field()
    """
    The text content. It may contain citation markers, each a number in square
    brackets such as `[1]`. The `start_index` and `end_index` fields of a citation
    indicate the location of its marker. To resolve a marker, find the citation at
    that location. Not every marker has a matching citation; when a marker has
    none, treat it as a citation you cannot display, not as an error.
    """

    annotations: typing.List[ResponseAnnotation] = pydantic.Field()
    """
    Citations that tie spans of the `text` field to what they cite, in order of
    appearance. Always present, and may be empty.
    
    The `start_index` and `end_index` fields locate the marker within the
    `text` field of this content part, not within the whole response.
    
    Different citations can cover the same or overlapping video ranges. Each
    marker in the `text` field still resolves to at most one citation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
