# This file was auto-generated by Fern from our API Definition.

import typing

ResponseAnnotationType = typing.Union[
    typing.Literal["video_citation", "image_citation", "collection_citation"], typing.Any
]
