# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .response_object import ResponseObject
from .response_stream_event_base import ResponseStreamEventBase


class ResponseStreamResponseEvent(ResponseStreamEventBase):
    """
    Wraps a response object. Emitted for `response.created`, `response.in_progress`,
    `response.completed`, and `response.failed` events.
    """

    response: typing.Optional[ResponseObject] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
