# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .response_object import ResponseObject
from .response_output_content_part import ResponseOutputContentPart
from .response_output_item import ResponseOutputItem


class ResponseStreamEvent_ResponseCreated(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.created"] = "response.created"
    response: typing.Optional[ResponseObject] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseInProgress(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.in_progress"] = "response.in_progress"
    response: typing.Optional[ResponseObject] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseCompleted(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.completed"] = "response.completed"
    response: typing.Optional[ResponseObject] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseFailed(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.failed"] = "response.failed"
    response: typing.Optional[ResponseObject] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseOutputItemAdded(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.output_item.added"] = "response.output_item.added"
    output_index: typing.Optional[int] = None
    item: typing.Optional[ResponseOutputItem] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseContentPartAdded(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.content_part.added"] = "response.content_part.added"
    item_id: typing.Optional[str] = None
    output_index: typing.Optional[int] = None
    content_index: typing.Optional[int] = None
    part: typing.Optional[ResponseOutputContentPart] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseOutputTextDelta(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.output_text.delta"] = "response.output_text.delta"
    item_id: typing.Optional[str] = None
    output_index: typing.Optional[int] = None
    content_index: typing.Optional[int] = None
    delta: typing.Optional[str] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseOutputTextDone(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.output_text.done"] = "response.output_text.done"
    item_id: typing.Optional[str] = None
    output_index: typing.Optional[int] = None
    content_index: typing.Optional[int] = None
    text: typing.Optional[str] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseContentPartDone(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.content_part.done"] = "response.content_part.done"
    item_id: typing.Optional[str] = None
    output_index: typing.Optional[int] = None
    content_index: typing.Optional[int] = None
    part: typing.Optional[ResponseOutputContentPart] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseOutputItemDone(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.output_item.done"] = "response.output_item.done"
    output_index: typing.Optional[int] = None
    item: typing.Optional[ResponseOutputItem] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ResponseStreamEvent_ResponseFunctionCallArgumentsDone(UniversalBaseModel):
    """
    A Server-Sent Event emitted during a streaming response.
    Events use [Open Responses streaming](https://www.openresponses.org/specification#streaming) conventions.

    The stream consists of events with a `type` field indicating the event kind:
    - `response.created` — Initial event with the response object in `in_progress` state.
    - `response.in_progress` — The response is being generated.
    - `response.output_item.added` — A new output item has started.
    - `response.content_part.added` — A new content part has started within a message.
    - `response.output_text.delta` — An incremental text chunk.
    - `response.output_text.done` — Text streaming for a content part is complete.
    - `response.content_part.done` — A content part is finalized.
    - `response.function_call_arguments.done` — Function call arguments are complete.
    - `response.output_item.done` — An output item is finalized.
    - `response.completed` — The response is complete.
    - `response.failed` — The response has failed.

    The stream ends with a `data: [DONE]` message.
    """

    type: typing.Literal["response.function_call_arguments.done"] = "response.function_call_arguments.done"
    item_id: typing.Optional[str] = None
    output_index: typing.Optional[int] = None
    arguments: typing.Optional[str] = None
    sequence_number: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ResponseStreamEvent = typing.Union[
    ResponseStreamEvent_ResponseCreated,
    ResponseStreamEvent_ResponseInProgress,
    ResponseStreamEvent_ResponseCompleted,
    ResponseStreamEvent_ResponseFailed,
    ResponseStreamEvent_ResponseOutputItemAdded,
    ResponseStreamEvent_ResponseContentPartAdded,
    ResponseStreamEvent_ResponseOutputTextDelta,
    ResponseStreamEvent_ResponseOutputTextDone,
    ResponseStreamEvent_ResponseContentPartDone,
    ResponseStreamEvent_ResponseOutputItemDone,
    ResponseStreamEvent_ResponseFunctionCallArgumentsDone,
]
