# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .response_create_request_include_item import ResponseCreateRequestIncludeItem
from .response_input_item import ResponseInputItem
from .response_selection import ResponseSelection
from .text_param import TextParam


class ResponseCreateRequest(UniversalBaseModel):
    """
    Request body for the Responses endpoint.
    """

    knowledge_store_id: str = pydantic.Field()
    """
    The unique identifier of the knowledge store to reason over.
    """

    input: typing.List[ResponseInputItem] = pydantic.Field()
    """
    Provides context to Jockey for this request. Uses [Open Responses input item](https://www.openresponses.org/reference#input-items) conventions.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The session identifier for a multi-turn conversation. Pass the session identifier
    returned from a previous response to continue that conversation. Omit to start
    a new session.
    
    When provided, the `knowledge_store_id` field must match the knowledge store the session
    was originally created against, or the request returns `400`.
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional guidance for Jockey, acting as a per-request system prompt.
    """

    include: typing.Optional[typing.List[ResponseCreateRequestIncludeItem]] = pydantic.Field(default=None)
    """
    Additional items to include in the response's `output` array. By default, the `output` array contains only Jockey's final reply.
    
    **Values**:
    - `intermediate_outputs`: Also includes the steps Jockey took to produce the reply.
    """

    stream: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When `true`, the response is returned as [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) (SSE).
    """

    selections: typing.Optional[typing.List[ResponseSelection]] = pydantic.Field(default=None)
    """
    Restricts the request to specific knowledge store items or item collections. The restriction is applied at the prompt level; the knowledge store does not block access to other items. Treat it as a strong preference, not a hard access boundary. Omit to run against every item.
    
    Selections persist in the session context, and selections sent on later turns are added to that context. You can reference selections from earlier turns in natural language without repeating their `{{sel:N}}` tokens.
    """

    text: typing.Optional[TextParam] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
