# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .response_object_type import ResponseObjectType
from .response_output_item import ResponseOutputItem
from .response_status import ResponseStatus
from .response_usage import ResponseUsage


class ResponseObject(UniversalBaseModel):
    """
    The response object.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for this response.
    """

    knowledge_store_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the knowledge store this response was generated against.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The session identifier for this conversation. Pass this value in subsequent requests to continue
    the multi-turn conversation.
    """

    type: typing.Optional[ResponseObjectType] = pydantic.Field(default=None)
    """
    The object type. Always `response`.
    """

    status: typing.Optional[ResponseStatus] = None
    output: typing.Optional[typing.List[ResponseOutputItem]] = pydantic.Field(default=None)
    """
    The response output items. By default, only the final message is included.
    Set `include` to `["intermediate_outputs"]` in the request to receive function call items.
    """

    usage: typing.Optional[ResponseUsage] = None
    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The timestamp when the response was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
