# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .response_stream_event_base import ResponseStreamEventBase


class ResponseStreamKeepAliveEvent(ResponseStreamEventBase):
    """
    A heartbeat frame the server sends about every 10 seconds when no other
    event has been emitted, for example while a tool call is still running.
    It carries no response data. Use it to keep the connection alive and to
    detect stalled streams; otherwise you can ignore it.

    `sequence_number` uses the same counter as all other event types. If you
    skip keepalive frames, the numbers you see will have gaps; these gaps do
    not mean events were dropped.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
