# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_search_item_metadata import ImageSearchItemMetadata
from .video_match import VideoMatch
from .video_search_item_metadata import VideoSearchItemMetadata


class SearchKnowledgeStoreHit_Video(UniversalBaseModel):
    """
    A single result in the search response. The fields present depend on the `asset_type` field.
    """

    asset_type: typing.Literal["video"] = "video"
    rank: int
    item_id: str
    metadata: typing.Optional[VideoSearchItemMetadata] = None
    matches: typing.List[VideoMatch]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SearchKnowledgeStoreHit_Image(UniversalBaseModel):
    """
    A single result in the search response. The fields present depend on the `asset_type` field.
    """

    asset_type: typing.Literal["image"] = "image"
    rank: int
    item_id: str
    metadata: typing.Optional[ImageSearchItemMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SearchKnowledgeStoreHit = typing.Union[SearchKnowledgeStoreHit_Video, SearchKnowledgeStoreHit_Image]
