# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .next_page_token import NextPageToken
from .search_knowledge_store_hit import SearchKnowledgeStoreHit
from .search_knowledge_store_options import SearchKnowledgeStoreOptions


class SearchKnowledgeStoreResponse(UniversalBaseModel):
    """
    The search results. Each entry in the `data` array includes an `asset_type` field that indicates the type of item.
    """

    data: typing.List[SearchKnowledgeStoreHit] = pydantic.Field()
    """
    Search results, ordered by relevance.
    """

    next_page_token: typing.Optional[NextPageToken] = pydantic.Field(default=None)
    """
    Pagination token for the next page. Pass this value as the `page_token` parameter in your next request to retrieve more results. Absent when no more pages exist.
    """

    effective_search_options: SearchKnowledgeStoreOptions = pydantic.Field()
    """
    The video options applied to this search, including any defaults.
    
    - **When the search includes videos**: this object contains a `video` field with the modalities used.
    - **When the search is limited to images** (the `filter.asset_type` field excludes videos): no video options apply, and this object is empty.
    
    Any option you omit is returned with its default value. For example, the `video` field shows `["visual"]` for modalities when you don't set `search_options.video`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
