# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .asset_type_filter import AssetTypeFilter
from .item_id_filter import ItemIdFilter


class SearchKnowledgeStoreFilter(UniversalBaseModel):
    """
    Narrows results to specific items in the knowledge store.

    Filter by type of item (the `asset_type` field) or by specific identifiers (the `item_id` field). Use `eq` to match a single value or `in` to match any value in a list. When you specify multiple fields, the platform applies all conditions together.

    Examples:
    ```json
    {
        "asset_type": {
            "eq": "video"
        }
    }
    ```
    ```json
    {
        "asset_type": {
            "in": [
                "video"
            ]
        },
        "item_id": {
            "in": [
                "ksi_069e9870-3c4d-7abc-9012-3456789abcde"
            ]
        }
    }
    ```

    Omit the filter to search all items.
    """

    asset_type: typing.Optional[AssetTypeFilter] = None
    item_id: typing.Optional[ItemIdFilter] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
