# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .segment_field_items import SegmentFieldItems
from .segment_field_type import SegmentFieldType


class SegmentField(UniversalBaseModel):
    """
    A custom field to extract for each segment.
    """

    name: str = pydantic.Field()
    """
    The name of the field.
    """

    type: SegmentFieldType = pydantic.Field()
    """
    The data type of the field.
    """

    description: str = pydantic.Field()
    """
    Instructions that guide the model on what this field should contain and how to extract it from the video.
    """

    enum: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Allowed values for this field. Maximum 50 values.
    """

    items: typing.Optional[SegmentFieldItems] = pydantic.Field(default=None)
    """
    Required when `type` is `array`. Specifies the type of array elements.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
