# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sync_response_format_type import SyncResponseFormatType


class SyncResponseFormat(UniversalBaseModel):
    """
    Specifies the format of the response. When you omit this parameter, the platform returns unstructured text.
    """

    type: SyncResponseFormatType = pydantic.Field()
    """
    Set this parameter to "json_schema" to receive structured JSON responses.
    """

    json_schema: typing.Dict[str, typing.Optional[typing.Any]] = pydantic.Field()
    """
    Contains the JSON schema that defines the response structure. The schema must adhere to the [JSON Schema Draft 2020-12](https://json-schema.org/draft/2020-12) specification.
    
    **Supported types**
    - `array`
    - `boolean`
    - `integer`
    - `null`
    - `number`
    - `object`
    - `string`
    - `timestamp` (Pegasus 1.5 only)
    
    **Supported constraints**
    
    | Type | Supported keywords | Notes |
    |------|-------------------|-------|
    | `integer` | `maximum`, `exclusiveMaximum`, `minimum`, `exclusiveMinimum`. | - `maximum`: Sets the highest allowed value (inclusive).<br/>- `exclusiveMaximum`: Sets the highest allowed value (exclusive).<br/>- `minimum`: Sets the lowest allowed value (inclusive).<br/>- `exclusiveMinimum`: Sets the lowest allowed value (exclusive).<br/>These constraints are supported only for the `integer` type. |
    | `string` | `pattern`, `format` | - `pattern`: A regular expression that the string must match.<br/>- `format`: Validates predefined formats. It accepts the following values: `uuid`, `date-time`, `date`, and `time`.<br/>See string limitations below. |
    | `object` | `properties`, `required` | - `properties`: Defines object properties and their schemas. - `required`: Specifies mandatory properties.<br/>See object limitations below. |
    | `array` | `items`, `minItems` | `minItems` accepts only `0` or `1`.<br/>See array limitations below. |
    | `timestamp` | `format` | `format` (required): Sets the output format. Accepted values: `seconds`, `hh:mm:ss`, `hh:mm:ss.fff`.<br/>See the **Timestamp type** section below. |
    
    
    **String limitations**
    
    When you use the `string` type:
    - The platform validates strings using only `pattern` and `format`. Including `minLength` or `maxLength` causes a 422 error: "String length constraints (minLength) are not supported." Remove these keywords from your schema.
    
    
    **Object limitations**
    
    When you use the `object` type:
    - The platform does not support the `additionalProperties` keyword. Including it causes a 422 error. Remove it from your schema.
    - The platform returns properties in declaration order.
    - Make the first property required. If the first property is optional, the platform moves the first required property to the beginning.
    
    
    **Array limitations**
    
    When you use the `array` type:
    - The platform does not support `uniqueItems` or `maxItems`. Including either keyword causes a 422 error. Remove them from your schema.
    
    
    **Constant and enumerated values**
    
    The `const` and `enum` keywords support the following types:
    - `boolean`
    - `null`
    - `number`
    - `string`
    
    
    **Schema composition**
    
    The platform supports only `anyOf` for [schema composition](https://json-schema.org/understanding-json-schema/reference/combining).
    
    
    **Annotations**
    
    The platform accepts but ignores JSON schema annotations like `title`, `$comments`, and `description`.
    
    **Subschema references**
    
    You can reference subschemas using `$ref` with these requirements:
    - Define subschemas within `$defs`.
    - Use valid URIs that point to the internal subschema.
    
    For details, see the [JSON Schema documentation on $defs](https://json-schema.org/understanding-json-schema/structuring#defs).
    
    
    **Timestamp type (Pegasus 1.5 only)**
    
    Declare a property as `{"type": "timestamp", "format": "<format>"}` to control the format of the returned value.
    
    The `format` field accepts the following values:
    
    | `format` | Example output | Notes |
    |----------|----------------|-------|
    | `seconds` | `10.5` | Returns a JSON number in seconds. |
    | `hh:mm:ss` | `"00:01:23"` | Rounded to the nearest second. Negative values are converted to `"00:00:00"`. |
    | `hh:mm:ss.fff` | `"00:01:23.500"` | Millisecond precision. |
    
    The type of the response depends on the value of the `format` field: `seconds` returns a JSON number, while `hh:mm:ss` and `hh:mm:ss.fff` return a JSON string.
    
    *Supported positions*
    
    You can declare `timestamp` fields at the top level of your schema or inside objects nested one level within an array:
    
    - Top level: `properties.<field_name>`
    - Inside an array: `properties.<array_field>.items.properties.<field_name>`
    
    Declaring `timestamp` outside these positions — deeper nesting, inside `oneOf` / `anyOf` / `allOf`, or inside `$ref` — is not supported and is rejected with HTTP 400.
    
    *Validation errors*
    
    When `format` is missing or invalid, the platform returns `400 parameter_invalid`:
    
    ```
    response_format.json_schema.properties.<name>.format: format is required for timestamp type; allowed values: seconds, hh:mm:ss, hh:mm:ss.fff
    ```
    
    
    **Reserved property names (`start_time` / `end_time`)**
    
    For Pegasus 1.5, properties named `start_time` or `end_time` in your response schema receive special type handling at any nesting depth (including inside array `items`). These are unrelated to the top-level `start_time` / `end_time` request parameters. The platform returns the value in a format determined by the declared type:
    
    *Allowed declarations:*
    
    | Declared type | Platform behavior |
    |---------------|-------------------|
    | `number` | Passes the value through without conversion. |
    | `integer` | Rounds the value to the nearest integer. |
    | `string` (no `format`) | Converts the value to the `hh:mm:ss.fff` format. |
    | `timestamp` with `format` | See the **Timestamp type** section above for the available formats. |
    
    *Rejected declarations (returns `400` error):*
    - `string` with any `format` keyword (`time`, `date-time`, `email`, `uri`, etc.)
    - `boolean`
    - `object`
    - `array`
    - `null`
    
    All other property names in your schema remain unconstrained by these rules. For other field names, use the `timestamp` type described above.
    
    
    **Response validation**
    
    Check the `FinishReason` field to verify your JSON response is complete:
    - When `FinishReason` is `stop`, the generation completed normally, and the JSON is valid and complete.
    - When `FinishReason` is `length`, the platform truncates the response at the maximum response length or the context window. This may result in truncated, invalid JSON that fails to parse.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
