# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audio_stream import AudioStream
from .video_stream import VideoStream


class TechnicalMetadata(UniversalBaseModel):
    """
    Technical metadata read from the source file of the asset, covering the container, video and audio streams, image properties, document properties, and derived attributes.

    The platform populates this object asynchronously after the upload completes. It is omitted from the response while the status of the asset is `processing`, and it may be partially populated when the status is `failed`. A field is absent when it does not apply to the type of the asset or when the source file did not contain the corresponding information.
    """

    file_size_bytes: typing.Optional[int] = pydantic.Field(default=None)
    """
    The size of the source file in bytes.
    """

    file_mime_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The MIME type detected for the source file.
    """

    file_container_format: typing.Optional[str] = pydantic.Field(default=None)
    """
    The container format of the source file. When a container maps to several format names, the platform reports them as a comma-separated list.
    """

    container_creation_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The creation time recorded in the source file container, in RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when present.
    """

    video_streams: typing.Optional[typing.List[VideoStream]] = pydantic.Field(default=None)
    """
    The video streams contained in the media file.
    """

    video_codec: typing.Optional[str] = pydantic.Field(default=None)
    """
    The codec of the primary video stream.
    """

    video_width: typing.Optional[int] = pydantic.Field(default=None)
    """
    The pixel width of the primary video stream.
    """

    video_height: typing.Optional[int] = pydantic.Field(default=None)
    """
    The pixel height of the primary video stream.
    """

    video_fps: typing.Optional[float] = pydantic.Field(default=None)
    """
    The frame rate of the primary video stream, in frames per second.
    """

    video_duration_seconds: typing.Optional[float] = pydantic.Field(default=None)
    """
    The duration of the primary video stream, in seconds.
    """

    video_bitrate_bps: typing.Optional[int] = pydantic.Field(default=None)
    """
    The bit rate of the primary video stream, in bits per second.
    """

    audio_streams: typing.Optional[typing.List[AudioStream]] = pydantic.Field(default=None)
    """
    The audio streams contained in the media file.
    """

    audio_codec: typing.Optional[str] = pydantic.Field(default=None)
    """
    The codec of the primary audio stream.
    """

    audio_sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    The sample rate of the primary audio stream, in hertz.
    """

    audio_channels: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of channels in the primary audio stream.
    """

    audio_duration_seconds: typing.Optional[float] = pydantic.Field(default=None)
    """
    The duration of the primary audio stream, in seconds.
    """

    start_timecode: typing.Optional[str] = pydantic.Field(default=None)
    """
    The starting SMPTE timecode of the media, when present.
    """

    timecode_source: typing.Optional[str] = pydantic.Field(default=None)
    """
    The source from which the starting timecode was derived.
    """

    drop_frame: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the timecode uses drop-frame numbering.
    """

    image_width: typing.Optional[int] = pydantic.Field(default=None)
    """
    The pixel width of the image.
    """

    image_height: typing.Optional[int] = pydantic.Field(default=None)
    """
    The pixel height of the image.
    """

    image_format: typing.Optional[str] = pydantic.Field(default=None)
    """
    The format of the image.
    """

    image_orientation: typing.Optional[int] = pydantic.Field(default=None)
    """
    The EXIF orientation value of the image.
    """

    image_color_space: typing.Optional[str] = pydantic.Field(default=None)
    """
    The color space of the image.
    """

    image_bit_depth: typing.Optional[int] = pydantic.Field(default=None)
    """
    The bit depth per channel of the image.
    """

    is_hdr: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the media is high dynamic range (HDR).
    """

    has_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the media contains at least one audio stream.
    """

    has_alpha: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the image contains an alpha (transparency) channel.
    """

    is_animated: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the image is animated (for example, an animated GIF or WebP).
    """

    total_video_streams: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of video streams in the media file.
    """

    total_audio_streams: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of audio streams in the media file.
    """

    storage_aspect_ratio: typing.Optional[float] = pydantic.Field(default=None)
    """
    The storage aspect ratio of the video (pixel width divided by pixel height).
    """

    geospatial_latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The GPS latitude embedded in the source media, in decimal degrees. Present only when the source media carries location metadata.
    """

    geospatial_longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The GPS longitude embedded in the source media, in decimal degrees. Present only when the source media carries location metadata.
    """

    geospatial_altitude_meters: typing.Optional[float] = pydantic.Field(default=None)
    """
    The GPS altitude embedded in the source media, in meters. Present only when the source media carries location metadata.
    """

    document_page_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of pages in the PDF file.
    """

    document_pdf_version: typing.Optional[str] = pydantic.Field(default=None)
    """
    The PDF version specified in the file.
    """

    document_page_width_pt: typing.Optional[float] = pydantic.Field(default=None)
    """
    The width of the first page, in points.
    """

    document_page_height_pt: typing.Optional[float] = pydantic.Field(default=None)
    """
    The height of the first page, in points.
    """

    document_is_tagged: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the PDF file is tagged for accessibility. An explicit `false` is meaningful.
    """

    document_is_encrypted: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the PDF file is encrypted. An explicit `false` is meaningful.
    """

    document_language: typing.Optional[str] = pydantic.Field(default=None)
    """
    The language specified in the PDF file, when present.
    """

    document_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The title from the PDF metadata, when present.
    """

    document_author: typing.Optional[str] = pydantic.Field(default=None)
    """
    The author from the PDF metadata, when present.
    """

    document_subject: typing.Optional[str] = pydantic.Field(default=None)
    """
    The subject from the PDF metadata, when present.
    """

    document_keywords: typing.Optional[str] = pydantic.Field(default=None)
    """
    The keywords from the PDF metadata, when present.
    """

    document_creator_tool: typing.Optional[str] = pydantic.Field(default=None)
    """
    The application that created the PDF file, when present.
    """

    document_producer: typing.Optional[str] = pydantic.Field(default=None)
    """
    The application that produced the PDF file, when present.
    """

    document_creation_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The normalized creation date from the PDF file, in RFC 3339 format, when present.
    """

    document_modification_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The normalized modification date from the PDF file, in RFC 3339 format, when present.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
