# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TemporalSegmentationDynamicDynamic(UniversalBaseModel):
    """
    Configuration for dynamic segmentation. This object is required when `strategy` is `dynamic`.
    """

    min_duration_sec: int = pydantic.Field()
    """
    The minimum duration in seconds for each segment.
    
    The platform divides the file into segments that are at least this long. Segments adapt to scene changes and content boundaries and may be longer than the minimum.
    
    **Min**: `2`.
    **Max**: `5`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
