# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_metadata import UserMetadata
from .video_search_system_metadata import VideoSearchSystemMetadata


class VideoSearchItemMetadata(UniversalBaseModel):
    """
    Metadata attached to a video knowledge store item in search results.
    """

    system: typing.Optional[VideoSearchSystemMetadata] = pydantic.Field(default=None)
    """
    System-generated media metadata for the source video.
    """

    user: typing.Optional[UserMetadata] = pydantic.Field(default=None)
    """
    Caller-supplied key-value pairs attached to the item.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
