# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.page_info import PageInfo
from ...types.redirect_uri import RedirectUri


class ListRedirectUrisResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[RedirectUri]] = pydantic.Field(default=None)
    """
    An array containing the redirect URIs.
    """

    page_info: typing.Optional[PageInfo] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
