# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.ingestion_config import IngestionConfig
from ..types.knowledge_store import KnowledgeStore
from ..types.knowledge_store_search_query import KnowledgeStoreSearchQuery
from ..types.search_knowledge_store_filter import SearchKnowledgeStoreFilter
from ..types.search_knowledge_store_options import SearchKnowledgeStoreOptions
from ..types.search_knowledge_store_response import SearchKnowledgeStoreResponse
from .raw_client import AsyncRawKnowledgeStoresClient, RawKnowledgeStoresClient
from .types.knowledge_stores_list_request_sort_by import KnowledgeStoresListRequestSortBy
from .types.search_knowledge_store_request_group_by import SearchKnowledgeStoreRequestGroupBy

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class KnowledgeStoresClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawKnowledgeStoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawKnowledgeStoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawKnowledgeStoresClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_limit: typing.Optional[int] = None,
        sort_by: typing.Optional[KnowledgeStoresListRequestSortBy] = None,
        sort_option: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[KnowledgeStore]:
        """
        This method returns a list of the knowledge stores in your account.

        Parameters
        ----------
        page : typing.Optional[int]
            A number that identifies the page to retrieve.

            **Default**: `1`.

        page_limit : typing.Optional[int]
            The number of items to return on each page.

            **Default**: `10`.
            **Max**: `50`.

        sort_by : typing.Optional[KnowledgeStoresListRequestSortBy]
            The field to sort on. The following options are available:
            - `created_at`: Sorts by the time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the knowledge store was created.
            - `updated_at`: Sorts by the time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the knowledge store was updated.

            **Default**: `created_at`.

        sort_option : typing.Optional[str]
            The sorting direction. The following options are available:
            - `asc`
            - `desc`

            **Default**: `desc`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[KnowledgeStore]
            The knowledge stores have been successfully retrieved.

        Examples
        --------
        from twelvelabs import TwelveLabs

        client = TwelveLabs(
            api_key="YOUR_API_KEY",
        )
        response = client.knowledge_stores.list(
            page=1,
            page_limit=10,
            sort_by="created_at",
            sort_option="desc",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            page=page, page_limit=page_limit, sort_by=sort_by, sort_option=sort_option, request_options=request_options
        )

    def create(
        self,
        *,
        name: str,
        ingestion_config: typing.Optional[IngestionConfig] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KnowledgeStore:
        """
        This method creates a knowledge store.

        Provide a name. Optionally include a description, a metadata map, and an `ingestion_config` object that controls how content added to the store is processed. The `ingestion_config` object is immutable after creation.

        Parameters
        ----------
        name : str
            The name of the knowledge store.

        ingestion_config : typing.Optional[IngestionConfig]

        description : typing.Optional[str]
            An optional description of the knowledge store.

        metadata : typing.Optional[typing.Dict[str, str]]
            Custom metadata for the knowledge store. Both keys and values must be strings.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KnowledgeStore
            The knowledge store has been successfully created.

        Examples
        --------
        from twelvelabs import TwelveLabs

        client = TwelveLabs(
            api_key="YOUR_API_KEY",
        )
        client.knowledge_stores.create(
            name="Product Demo Analysis",
        )
        """
        _response = self._raw_client.create(
            name=name,
            ingestion_config=ingestion_config,
            description=description,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def retrieve(
        self, knowledge_store_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> KnowledgeStore:
        """
        This method retrieves the details of a specific knowledge store.

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KnowledgeStore
            The knowledge store has been successfully retrieved.

        Examples
        --------
        from twelvelabs import TwelveLabs

        client = TwelveLabs(
            api_key="YOUR_API_KEY",
        )
        client.knowledge_stores.retrieve(
            knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
        )
        """
        _response = self._raw_client.retrieve(knowledge_store_id, request_options=request_options)
        return _response.data

    def delete(self, knowledge_store_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This method deletes the specified knowledge store and all its items.

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from twelvelabs import TwelveLabs

        client = TwelveLabs(
            api_key="YOUR_API_KEY",
        )
        client.knowledge_stores.delete(
            knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
        )
        """
        _response = self._raw_client.delete(knowledge_store_id, request_options=request_options)
        return _response.data

    def update(
        self,
        knowledge_store_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KnowledgeStore:
        """
        This method updates the specified knowledge store. Only the `name`, `description`, and `metadata` fields can be updated.

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        name : typing.Optional[str]
            The name of the knowledge store.

        description : typing.Optional[str]
            An optional description of the knowledge store.

        metadata : typing.Optional[typing.Dict[str, str]]
            Custom metadata for the knowledge store. Both keys and values must be strings. The provided object replaces the existing metadata in full, so include every key you want to keep. To clear all metadata, set this field to an empty object (`{}`). A null value is stored as an empty string.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KnowledgeStore
            The knowledge store has been successfully updated.

        Examples
        --------
        from twelvelabs import TwelveLabs

        client = TwelveLabs(
            api_key="YOUR_API_KEY",
        )
        client.knowledge_stores.update(
            knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
        )
        """
        _response = self._raw_client.update(
            knowledge_store_id, name=name, description=description, metadata=metadata, request_options=request_options
        )
        return _response.data

    def search(
        self,
        knowledge_store_id: str,
        *,
        query: KnowledgeStoreSearchQuery,
        filter: typing.Optional[SearchKnowledgeStoreFilter] = OMIT,
        search_options: typing.Optional[SearchKnowledgeStoreOptions] = OMIT,
        group_by: typing.Optional[SearchKnowledgeStoreRequestGroupBy] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        page_token: typing.Optional[str] = OMIT,
        include_metadata: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchKnowledgeStoreResponse:
        """
        This method searches a knowledge store using natural language and returns matching video clips and images ranked by relevance.

        Provide your natural-language query in the `query.text` field. Use the `filter` parameter to choose which items to search: by type of item (the `asset_type` field) or by specific items (the `item_id` field). Use the optional `search_options` parameter to control how videos are matched (by visual content, audio, or both). If you omit it, videos are matched on their visual content. Images are always matched on their visual content.

        By default, each result is an individual match: a video clip or an image. Set the `group_by` parameter to `item` to group clips under their parent item.

        <Note title="Note">
        This endpoint is rate-limited. For details, see the [Rate limits](/v1.3/docs/get-started/rate-limits) page.
        </Note>

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        query : KnowledgeStoreSearchQuery

        filter : typing.Optional[SearchKnowledgeStoreFilter]

        search_options : typing.Optional[SearchKnowledgeStoreOptions]

        group_by : typing.Optional[SearchKnowledgeStoreRequestGroupBy]
            Controls how the platform groups matches in the response.

            - `none`: Returns individual matches ordered by relevance.
            - `item`: Groups matches under their parent item.

            **Default**: `none`.

        page_size : typing.Optional[int]
            The maximum number of results per page. A result is one entry in the `data` array. With the `group_by` parameter set to its default of `none`, each result is an individual match: a video clip or an image. When set to `item`, each result is one item: a video with all its matching clips, or an image.

            **Default**: `10`. **Max**: `50`.

        page_token : typing.Optional[str]
            Pagination token used to retrieve the next page of results. Omit it on the first request. To fetch the next page, set it to the `next_page_token` field returned in the previous response and send the request again.

            A malformed or unrecognized token returns a `400` error. A token that has expired returns a `410` error (make a new search request to obtain a fresh page token).

        include_metadata : typing.Optional[bool]
            Set to `true` to include metadata in each result. Each result includes a `metadata` object with a `system` field (platform-derived file properties such as duration and resolution) and a `user` field (metadata you attached to the item).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchKnowledgeStoreResponse
            The search completed successfully.

        Examples
        --------
        from twelvelabs import (
            KnowledgeStoreSearchQuery,
            SearchKnowledgeStoreOptions,
            TwelveLabs,
            VideoSearchOptions,
        )

        client = TwelveLabs(
            api_key="YOUR_API_KEY",
        )
        client.knowledge_stores.search(
            knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
            query=KnowledgeStoreSearchQuery(
                text="A person cooking pasta",
            ),
            search_options=SearchKnowledgeStoreOptions(
                video=VideoSearchOptions(
                    modalities=["visual", "audio"],
                ),
            ),
            group_by="none",
            page_size=10,
        )
        """
        _response = self._raw_client.search(
            knowledge_store_id,
            query=query,
            filter=filter,
            search_options=search_options,
            group_by=group_by,
            page_size=page_size,
            page_token=page_token,
            include_metadata=include_metadata,
            request_options=request_options,
        )
        return _response.data


class AsyncKnowledgeStoresClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawKnowledgeStoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawKnowledgeStoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawKnowledgeStoresClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_limit: typing.Optional[int] = None,
        sort_by: typing.Optional[KnowledgeStoresListRequestSortBy] = None,
        sort_option: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[KnowledgeStore]:
        """
        This method returns a list of the knowledge stores in your account.

        Parameters
        ----------
        page : typing.Optional[int]
            A number that identifies the page to retrieve.

            **Default**: `1`.

        page_limit : typing.Optional[int]
            The number of items to return on each page.

            **Default**: `10`.
            **Max**: `50`.

        sort_by : typing.Optional[KnowledgeStoresListRequestSortBy]
            The field to sort on. The following options are available:
            - `created_at`: Sorts by the time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the knowledge store was created.
            - `updated_at`: Sorts by the time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the knowledge store was updated.

            **Default**: `created_at`.

        sort_option : typing.Optional[str]
            The sorting direction. The following options are available:
            - `asc`
            - `desc`

            **Default**: `desc`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[KnowledgeStore]
            The knowledge stores have been successfully retrieved.

        Examples
        --------
        import asyncio

        from twelvelabs import AsyncTwelveLabs

        client = AsyncTwelveLabs(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.knowledge_stores.list(
                page=1,
                page_limit=10,
                sort_by="created_at",
                sort_option="desc",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            page=page, page_limit=page_limit, sort_by=sort_by, sort_option=sort_option, request_options=request_options
        )

    async def create(
        self,
        *,
        name: str,
        ingestion_config: typing.Optional[IngestionConfig] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KnowledgeStore:
        """
        This method creates a knowledge store.

        Provide a name. Optionally include a description, a metadata map, and an `ingestion_config` object that controls how content added to the store is processed. The `ingestion_config` object is immutable after creation.

        Parameters
        ----------
        name : str
            The name of the knowledge store.

        ingestion_config : typing.Optional[IngestionConfig]

        description : typing.Optional[str]
            An optional description of the knowledge store.

        metadata : typing.Optional[typing.Dict[str, str]]
            Custom metadata for the knowledge store. Both keys and values must be strings.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KnowledgeStore
            The knowledge store has been successfully created.

        Examples
        --------
        import asyncio

        from twelvelabs import AsyncTwelveLabs

        client = AsyncTwelveLabs(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.knowledge_stores.create(
                name="Product Demo Analysis",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            ingestion_config=ingestion_config,
            description=description,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(
        self, knowledge_store_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> KnowledgeStore:
        """
        This method retrieves the details of a specific knowledge store.

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KnowledgeStore
            The knowledge store has been successfully retrieved.

        Examples
        --------
        import asyncio

        from twelvelabs import AsyncTwelveLabs

        client = AsyncTwelveLabs(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.knowledge_stores.retrieve(
                knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(knowledge_store_id, request_options=request_options)
        return _response.data

    async def delete(self, knowledge_store_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This method deletes the specified knowledge store and all its items.

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from twelvelabs import AsyncTwelveLabs

        client = AsyncTwelveLabs(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.knowledge_stores.delete(
                knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(knowledge_store_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        knowledge_store_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KnowledgeStore:
        """
        This method updates the specified knowledge store. Only the `name`, `description`, and `metadata` fields can be updated.

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        name : typing.Optional[str]
            The name of the knowledge store.

        description : typing.Optional[str]
            An optional description of the knowledge store.

        metadata : typing.Optional[typing.Dict[str, str]]
            Custom metadata for the knowledge store. Both keys and values must be strings. The provided object replaces the existing metadata in full, so include every key you want to keep. To clear all metadata, set this field to an empty object (`{}`). A null value is stored as an empty string.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KnowledgeStore
            The knowledge store has been successfully updated.

        Examples
        --------
        import asyncio

        from twelvelabs import AsyncTwelveLabs

        client = AsyncTwelveLabs(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.knowledge_stores.update(
                knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            knowledge_store_id, name=name, description=description, metadata=metadata, request_options=request_options
        )
        return _response.data

    async def search(
        self,
        knowledge_store_id: str,
        *,
        query: KnowledgeStoreSearchQuery,
        filter: typing.Optional[SearchKnowledgeStoreFilter] = OMIT,
        search_options: typing.Optional[SearchKnowledgeStoreOptions] = OMIT,
        group_by: typing.Optional[SearchKnowledgeStoreRequestGroupBy] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        page_token: typing.Optional[str] = OMIT,
        include_metadata: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchKnowledgeStoreResponse:
        """
        This method searches a knowledge store using natural language and returns matching video clips and images ranked by relevance.

        Provide your natural-language query in the `query.text` field. Use the `filter` parameter to choose which items to search: by type of item (the `asset_type` field) or by specific items (the `item_id` field). Use the optional `search_options` parameter to control how videos are matched (by visual content, audio, or both). If you omit it, videos are matched on their visual content. Images are always matched on their visual content.

        By default, each result is an individual match: a video clip or an image. Set the `group_by` parameter to `item` to group clips under their parent item.

        <Note title="Note">
        This endpoint is rate-limited. For details, see the [Rate limits](/v1.3/docs/get-started/rate-limits) page.
        </Note>

        Parameters
        ----------
        knowledge_store_id : str
            The unique identifier of the knowledge store.

        query : KnowledgeStoreSearchQuery

        filter : typing.Optional[SearchKnowledgeStoreFilter]

        search_options : typing.Optional[SearchKnowledgeStoreOptions]

        group_by : typing.Optional[SearchKnowledgeStoreRequestGroupBy]
            Controls how the platform groups matches in the response.

            - `none`: Returns individual matches ordered by relevance.
            - `item`: Groups matches under their parent item.

            **Default**: `none`.

        page_size : typing.Optional[int]
            The maximum number of results per page. A result is one entry in the `data` array. With the `group_by` parameter set to its default of `none`, each result is an individual match: a video clip or an image. When set to `item`, each result is one item: a video with all its matching clips, or an image.

            **Default**: `10`. **Max**: `50`.

        page_token : typing.Optional[str]
            Pagination token used to retrieve the next page of results. Omit it on the first request. To fetch the next page, set it to the `next_page_token` field returned in the previous response and send the request again.

            A malformed or unrecognized token returns a `400` error. A token that has expired returns a `410` error (make a new search request to obtain a fresh page token).

        include_metadata : typing.Optional[bool]
            Set to `true` to include metadata in each result. Each result includes a `metadata` object with a `system` field (platform-derived file properties such as duration and resolution) and a `user` field (metadata you attached to the item).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchKnowledgeStoreResponse
            The search completed successfully.

        Examples
        --------
        import asyncio

        from twelvelabs import (
            AsyncTwelveLabs,
            KnowledgeStoreSearchQuery,
            SearchKnowledgeStoreOptions,
            VideoSearchOptions,
        )

        client = AsyncTwelveLabs(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.knowledge_stores.search(
                knowledge_store_id="ks_069e9869-1ea3-7481-8000-dae72bf6be6e",
                query=KnowledgeStoreSearchQuery(
                    text="A person cooking pasta",
                ),
                search_options=SearchKnowledgeStoreOptions(
                    video=VideoSearchOptions(
                        modalities=["visual", "audio"],
                    ),
                ),
                group_by="none",
                page_size=10,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            knowledge_store_id,
            query=query,
            filter=filter,
            search_options=search_options,
            group_by=group_by,
            page_size=page_size,
            page_token=page_token,
            include_metadata=include_metadata,
            request_options=request_options,
        )
        return _response.data
