name: Version Management

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Version type"
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures tags are also fetched

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install bump2version
        run: pip install bump2version

      - name: Configure Git
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@twelvelabs.io"

      - name: Bump Version and Create Git Tag
        run: bump2version ${{ github.event.inputs.versionType }} --config-file .bumpversion.cfg

      - name: Push Changes
        run: |
          git push origin main --tags
